Test image, publish

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -20,23 +20,12 @@ env:
   PLATFORMS: linux/amd64,linux/arm64
 
 jobs:
-  build:
+  test:
     runs-on: ubuntu-22.04
-    timeout-minutes: 10
+    timeout-minutes: 20
 
     steps:
       - uses: actions/checkout@v4
-
-      - name: Decide whether to push image to registry
-        id: publish
-        run: |
-          PUSH=false
-          if [ "${{ startsWith(github.ref, 'refs/tags/') || (github.ref == format('refs/heads/{0}', env.PUBLISH_BRANCH)) }}" = "true" ]; then
-            if [ "${{ github.event_name }}" = "push" ]; then
-              PUSH=true
-            fi
-          fi
-          echo "push=$PUSH" >> $GITHUB_OUTPUT
 
       - uses: actions/setup-python@v5
         with:
@@ -51,6 +40,79 @@ jobs:
           path: |
             ~/.cache/ms-playwright
           key: ${{ runner.os }}-playwright
+
+      - name: Set up QEMU
+        uses: docker/setup-qemu-action@v3
+
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v3
+
+      - name: Build image
+        uses: docker/build-push-action@v6
+        with:
+          # Export to local Docker daemon so we can test it
+          load: true
+          tags: test
+          cache-from: type=gha
+          cache-to: type=gha,mode=max
+
+      - name: Install playwright
+        run: |
+          python -mpip install -r dev-requirements.txt
+          python -mplaywright install --with-deps
+
+      - name: Playwright browser test
+        run: |
+          container_id=$(docker run -d -it -p 8888:8888 -e JUPYTER_TOKEN=secret test)
+          sleep 3
+          export CONTAINER_ID=$container_id
+          export JUPYTER_HOST=http://localhost:8888
+          export JUPYTER_TOKEN=secret
+
+          python -mpytest -vs
+
+          echo "::group::jupyter_server logs"
+          docker logs $container_id
+          echo "::endgroup::"
+
+          echo "::group::vncserver logs"
+          docker exec $container_id bash -c 'cat ~/.vnc/*.log'
+          echo "::endgroup::"
+
+          timeout 5 docker stop $container_id > /dev/null && echo "Passed SIGTERM test" || { echo "Failed SIGTERM test" && TEST_OK=false; }
+
+          if [ "$TEST_OK" == "false" ]; then
+              echo "One or more tests failed!"
+              exit 1
+          fi
+
+      - name: Upload screenshot
+        uses: actions/upload-artifact@v4
+        if: always()
+        with:
+          name: screenshots
+          path: screenshots/*
+          if-no-files-found: error
+
+  publish:
+    runs-on: ubuntu-22.04
+    timeout-minutes: 60
+    needs:
+      - test
+
+    steps:
+      - uses: actions/checkout@v4
+
+      - name: Decide whether to push image to registry
+        id: publish
+        run: |
+          PUSH=false
+          if [ "${{ startsWith(github.ref, 'refs/tags/') || (github.ref == format('refs/heads/{0}', env.PUBLISH_BRANCH)) }}" = "true" ]; then
+            if [ "${{ github.event_name }}" = "push" ]; then
+              PUSH=true
+            fi
+          fi
+          echo "push=$PUSH" >> $GITHUB_OUTPUT
 
       - name: Docker meta
         id: meta
@@ -68,9 +130,20 @@ jobs:
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3
 
-      - name: Build image
+      - name: Login to container registry
+        uses: docker/login-action@v3
+        if: steps.publish.outputs.push == 'true'
+        with:
+          registry: ${{ env.REGISTRY }}
+          username: ${{ github.actor }}
+          password: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Build and push to container registry
         uses: docker/build-push-action@v6
         with:
-          # Export to local Docker daemon so we can test it
-          load: true
-          tags: test
+          platforms: ${{ env.PLATFORMS }}
+          tags: ${{ steps.meta.outputs.tags }}
+          labels: ${{ steps.meta.outputs.labels }}
+          push: ${{ steps.publish.outputs.push }}
+          cache-from: type=gha
+          cache-to: type=gha,mode=max
